// Generated by gencpp from file third_task/Coordinates.msg
// DO NOT EDIT!


#ifndef THIRD_TASK_MESSAGE_COORDINATES_H
#define THIRD_TASK_MESSAGE_COORDINATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace third_task
{
template <class ContainerAllocator>
struct Coordinates_
{
  typedef Coordinates_<ContainerAllocator> Type;

  Coordinates_()
    : x(0.0)
    , y(0.0)  {
    }
  Coordinates_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::third_task::Coordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::third_task::Coordinates_<ContainerAllocator> const> ConstPtr;

}; // struct Coordinates_

typedef ::third_task::Coordinates_<std::allocator<void> > Coordinates;

typedef boost::shared_ptr< ::third_task::Coordinates > CoordinatesPtr;
typedef boost::shared_ptr< ::third_task::Coordinates const> CoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::third_task::Coordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::third_task::Coordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::third_task::Coordinates_<ContainerAllocator1> & lhs, const ::third_task::Coordinates_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::third_task::Coordinates_<ContainerAllocator1> & lhs, const ::third_task::Coordinates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace third_task

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::third_task::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::third_task::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::third_task::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::third_task::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::third_task::Coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::third_task::Coordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::third_task::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::third_task::Coordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::third_task::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "third_task/Coordinates";
  }

  static const char* value(const ::third_task::Coordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::third_task::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# third_task/msg/Coordinates.msg\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::third_task::Coordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::third_task::Coordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Coordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::third_task::Coordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::third_task::Coordinates_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THIRD_TASK_MESSAGE_COORDINATES_H
