// Generated by gencpp from file third_task/Distance.msg
// DO NOT EDIT!


#ifndef THIRD_TASK_MESSAGE_DISTANCE_H
#define THIRD_TASK_MESSAGE_DISTANCE_H

#include <ros/service_traits.h>


#include <third_task/DistanceRequest.h>
#include <third_task/DistanceResponse.h>


namespace third_task
{

struct Distance
{

typedef DistanceRequest Request;
typedef DistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Distance
} // namespace third_task


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::third_task::Distance > {
  static const char* value()
  {
    return "a7986c87b5a540f05187a6ffc4756d6c";
  }

  static const char* value(const ::third_task::Distance&) { return value(); }
};

template<>
struct DataType< ::third_task::Distance > {
  static const char* value()
  {
    return "third_task/Distance";
  }

  static const char* value(const ::third_task::Distance&) { return value(); }
};


// service_traits::MD5Sum< ::third_task::DistanceRequest> should match
// service_traits::MD5Sum< ::third_task::Distance >
template<>
struct MD5Sum< ::third_task::DistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::third_task::Distance >::value();
  }
  static const char* value(const ::third_task::DistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::third_task::DistanceRequest> should match
// service_traits::DataType< ::third_task::Distance >
template<>
struct DataType< ::third_task::DistanceRequest>
{
  static const char* value()
  {
    return DataType< ::third_task::Distance >::value();
  }
  static const char* value(const ::third_task::DistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::third_task::DistanceResponse> should match
// service_traits::MD5Sum< ::third_task::Distance >
template<>
struct MD5Sum< ::third_task::DistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::third_task::Distance >::value();
  }
  static const char* value(const ::third_task::DistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::third_task::DistanceResponse> should match
// service_traits::DataType< ::third_task::Distance >
template<>
struct DataType< ::third_task::DistanceResponse>
{
  static const char* value()
  {
    return DataType< ::third_task::Distance >::value();
  }
  static const char* value(const ::third_task::DistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THIRD_TASK_MESSAGE_DISTANCE_H
